version: '3.9'
services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    restart: on-failure
    ports:
      - "8010:8010"
      - "9010:9010"
    environment:
      - CONFIG_MODE=local
    volumes:
      - ./configs/local.config.yaml:/app/configs/local.config.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 允许访问主机服务
    networks:
      - monitoring

#    grafana:
#      image: grafana/grafana:latest
#      container_name: grafana
#      ports:
#        - "3000:3000"
#      volumes:
#        - grafana_data:/var/lib/grafana
#        - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
#      environment:
#        - GF_SECURITY_ADMIN_USER=admin
#        - GF_SECURITY_ADMIN_PASSWORD=admin
#        - GF_USERS_ALLOW_SIGN_UP=false
#      depends_on:
#        - prometheus
#      networks:
#        - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
#  grafana_data:


# mysql:
#  image: mysql:latest
#  container_name: project_mysql
#  environment:
#    MYSQL_ROOT_PASSWORD: su1234
#    MYSQL_DATABASE: wisebase
#    MYSQL_USER: sider
#    MYSQL_PASSWORD: su1234
#  volumes:
#    - /home/dog/project_data/mysql:/var/lib/mysql
#  ports:
#    - "3306:3306"
