global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user_service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8010']  # 本地开发时访问宿主机服务
        labels:
          service: 'user-service'
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
